version = 1

test_patterns = ["test/*_test.go"]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/TunnelWork/payment.PayPal/v2"

[[transformers]]
name = "gofmt"
enabled = true